### ISSUE TITLE
怎么样去除字体的黑边

### ISSUE THREAD

**Issue by 102757017** [IMYR666/any-captcha#6]
生成的验证码边缘都产生了一圈黑色的描边，不想要该描边，怎么消除呢？

**Comment by IMYR666** [comment]
这个会对结果有影响吗

**Comment by IMYR666** [comment]
> 生成的验证码边缘都产生了一圈黑色的描边，不想要该描边，怎么消除呢？

这个会对结果有影响吗

**Comment by IMYR666** [comment]
> > 生成的验证码边缘都产生了一圈黑色的描边，不想要该描边，怎么消除呢？
> 
> 这个会对结果有影响吗

我检查了一下，你看到的黑边应该使用IDE打开图片的吧，使用其他图片查看器是没有的，所以这个黑边不是图片本身的

**Comment by 102757017** [comment]
> > > 生成的验证码边缘都产生了一圈黑色的描边，不想要该描边，怎么消除呢？
> > 
> > 
> > 这个会对结果有影响吗
> 
> 我检查了一下，你看到的黑边应该使用IDE打开图片的吧，使用其他图片查看器是没有的，所以这个黑边不是图片本身的

我不是用ide打开的图片，图片是保存在output文件夹的，我直接用系统自带的图片浏览器打开就是有黑边的状态，用“画图”打开编辑也可以看到黑边
![raE4](https://user-images.githubusercontent.com/30728579/55234124-615a6780-5265-11e9-95b0-7ebb70080cb9.jpg)

**Comment by IMYR666** [comment]
> > > > 生成的验证码边缘都产生了一圈黑色的描边，不想要该描边，怎么消除呢？
> > > 
> > > 
> > > 这个会对结果有影响吗
> > 
> > 
> > 我检查了一下，你看到的黑边应该使用IDE打开图片的吧，使用其他图片查看器是没有的，所以这个黑边不是图片本身的
> 
> 我不是用ide打开的图片，图片是保存在output文件夹的，我直接用系统自带的图片浏览器打开就是有黑边的状态，用“画图”打开编辑也可以看到黑边
> ![raE4](https://user-images.githubusercontent.com/30728579/55234124-615a6780-5265-11e9-95b0-7ebb70080cb9.jpg)

你上传的这张看不到黑边，而且也不是自己生成的吧

**Comment by 102757017** [comment]
> 你上传的这张看不到黑边，而且也不是自己生成的吧
上图字母确实有黑边压，字母E的边缘比较明显，下图更明显，字母W与字母D是同色的，交界处应该是看不出来的，但实际上有明显分界。
![WdKU](https://user-images.githubusercontent.com/30728579/55411863-f5476e80-5598-11e9-8ffa-0a70aa133ebf.jpg)
另外这个确实是用程序自动生成的，不过我把源码改了一下，只是干扰线改成了随机弧线，另外字符加了随机扭曲。
