### ISSUE TITLE
align不能设置为居中吗？

### ISSUE THREAD

**Issue by sharecj** [IMYR666/any-captcha#7]
align不能设置为居中吗？

**Comment by IMYR666** [comment]
考虑到随机偏移的存在，绝对的居中没有意义，你可以试试offset_hor=0, align=2看看能不能满足你的需求

**Comment by IMYR666** [comment]
> align不能设置为居中吗？

考虑到随机偏移的存在，绝对的居中没有意义，你可以试试offset_hor=0, align=2看看能不能满足你的需求
